global:
  baseapi: 'https://pool.energy/api/v1.0'
pool_stats:
  interval: 30
discord:
  token: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
  guild: '123456789012345678'
pool_actions:
  channel: '123456789012345678'
  webhook: 'https://discord.com/api/webhooks/123456789012345678/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
